version: '2.2'

services:
  rabbitmq:
    build: .
    image: rabitmq3.6-delay-message
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    ulimits:
      nproc: 65535
      nofile:
        soft: "65536"
        hard: "65536"
    mem_reservation: 512m
    mem_limit: 900m
    mem_swappiness: 0
    volumes:
     - 'rmq_data:/var/lib/rabbitmq'

volumes:
  rmq_data:
    driver: local