version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: redis-resturant-cache
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-rdb:/data